version: "3"

services:
  search:
    build: ./services/search
    ports:
      - "8080:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_UPSTREAM=http://api-proxy:8081
      - IMAGES_UPSTREAM=http://image-proxy:8082
      - API_KEY
      - NODE_ENV
    depends_on:
      - api-proxy
      - image-proxy

  api-proxy:
    build: ./services/api-proxy
    ports:
      - "8081:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - API_UPSTREAM
      - NODE_ENV

  image-proxy:
    build: ./services/image-proxy
    ports:
      - "8082:8080"
    environment:
      - HOST=0.0.0.0
      - PORT=8080
      - IMAGES_UPSTREAM
      - NODE_ENV
